name: Build alpha
on:
  workflow_dispatch:
    inputs:
      build_num:
        required: true
        type: choice
        default: "1"
        options: [1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 114514]

  push:
    branches:
      - 'dev'
    paths-ignore:
      - '**.md'
      - '**.txt'
      - '.github/**'
      - '.idea/**'
      - '!.github/workflows/build-alpha.yml'

jobs:
  prepare_publish_info:
    name: Prepare publish info
    runs-on: ubuntu-latest

    outputs:
      new_version: ${{ steps.update_version.outputs.new_version }}
      included_commits: ${{ steps.analyze_push_event.outputs.included_commits }}
      last_commit_hash: ${{ steps.analyze_push_event.outputs.last_commit_hash }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 解析push事件信息
        id: analyze_push_event
        run: |
          included_commits=$(git log ${{ github.event.before }}..HEAD --pretty="%h %s" --first-parent | jq -Rs '.')
          last_commit_hash=$(git log -1 --pretty="%H" --first-parent)
          echo "included_commits=$included_commits" >> $GITHUB_OUTPUT
          echo "last_commit_hash=$last_commit_hash" >> $GITHUB_OUTPUT

      - name: Get previous workflow run
        id: get_previous_run
        env:
          GITHUB_TOKEN: ${{ secrets.GIT_TOKEN }}
        run: |
          workflow_runs=$(curl -s -H "Authorization: token $GITHUB_TOKEN" \
            "https://api.github.com/repos/${{ github.repository }}/actions/workflows/${{ env.id }}/runs?status=completed&per_page=2")
          previous_run_id=$(echo $workflow_runs | jq -r '.workflow_runs[1].id')
          echo "Previous run ID: $previous_run_id"
          echo "previous_run_id=$previous_run_id" >> $GITHUB_ENV

      - name: 从artifact获取上次构建信息
        uses: actions/download-artifact@v4
        with:
          name: build_info
          run-id: ${{ env.previous_run_id }}

      - name: 生成alpha版本号
        id: update_version
        run: |
          last_tag=$(git tag --sort=committerdate | tail -1)
          version_name=$(yq e .version pubspec.yaml | cut -d "+" -f 1)
          version_code=$(echo $last_tag | cut -d "+" -f 2)

          if [[ ! -e build_info.yml && -z "${{ inputs.build_num }}" ]]; then
            echo "Neither build_info.yml exists nor specified build_num manually!"
            exit 1
          fi

          if (echo $last_tag | grep $version_name); then
            # 版本号一致，发行alpha版
            alpha_num=0
            if [[ -n "${{ inputs.build_num }}" ]]; then
              alpha_num=${{ inputs.build_num }}
            else
              let alpha_num=$(yq -r .build_num build_info.yml)+1
            fi
            echo "new_version=${version_name}-alpha.${alpha_num}+${version_code}" >> $GITHUB_OUTPUT
          else
            # 版本号不存在，发行pre版
            pre_num=0
            if [[ -n "${{ inputs.build_num }}" ]]; then
              pre_num=${{ inputs.build_num }}
            else
              if [[ $(yq -r .version build_info.yml) == $version_name ]]; then
                pre_num=$(yq -r .build_num build_info.yml)
              fi
              let ++pre_num
            fi
            echo "new_version=${version_name}-pre.${pre_num}+${version_code}" >> $GITHUB_OUTPUT
          fi

  build_matrix:
    name: Build CI (${{ matrix.target_platform }})
    needs: prepare_publish_info
    runs-on: ${{ matrix.build_os }}
    strategy:
      matrix:
        target_platform: [android-arm, android-arm64, android-x64, android-universal, iOS]
        include:
          - build_os: ubuntu-latest
          - target_platform: iOS
            build_os: macos-latest
              
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: 构建Java环境
        if: startsWith(matrix.target_platform, 'android')
        uses: actions/setup-java@v3
        with:
          distribution: "zulu"
          java-version: "21"
          token: ${{ secrets.GIT_TOKEN }}

      - name: 安装Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: 3.24.4
          channel: stable

      - name: 修复Flutter 3.24中文字重异常
        if: startsWith(matrix.target_platform, 'android')
        run: |
          cd $FLUTTER_ROOT
          git config --global user.name "orz12"
          git config --global user.email "orz12@test.com"
          git cherry-pick d4124bd --strategy-option theirs
          # Flutter precache
          flutter --version
          cd -

      - name: 下载项目依赖
        run: flutter pub get

      - name: 解码生成 jks
        if: startsWith(matrix.target_platform, 'android')
        run: echo $KEYSTORE_BASE64 | base64 -di > android/app/vvex.jks
        env: 
          KEYSTORE_BASE64: ${{ secrets.KEYSTORE_BASE64 }}

      - name: 更新版本号
        id: version
        run: |
          yq ".version=\"${{ needs.prepare_publish_info.outputs.new_version }}\"" pubspec.yaml > tmp.yaml
          mv tmp.yaml pubspec.yaml

      - name: flutter build apk (universal)
        if: matrix.target_platform == 'android-universal'
        run: flutter build apk --release
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: flutter build apk (${{ matrix.target_platform }})
        if: startsWith(matrix.target_platform, 'android') && matrix.target_platform != 'android-universal'
        run: flutter build apk --release --split-per-abi --target-platform=${{ matrix.target_platform }}
        env:
          KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
          KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
          KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}

      - name: flutter build ipa
        if: matrix.target_platform == 'iOS'
        run: |
          flutter build ios --release --no-codesign
          ln -sf ./build/ios/iphoneos Payload
          zip -r9 app.ipa Payload/runner.app

      - name: 重命名安装包(${{ matrix.target_platform }})
        if: startsWith(matrix.target_platform, 'android')
        run: |
          version_name=$(yq e .version pubspec.yaml | cut -d "+" -f 1)
          for file in build/app/outputs/flutter-apk/app-*.apk; do
            if [[ $file =~ app-(.?*)release.apk ]]; then
              new_file_name="build/app/outputs/flutter-apk/Pili-${BASH_REMATCH[1]}${version_name}.apk"
              mv "$file" "$new_file_name"
            fi
          done

      - name: 重命名安装包(iOS)
        if: matrix.target_platform == 'iOS'
        run: |
          for file in app.ipa; do
            new_file_name="build/Pili-${{ needs.prepare_publish_info.outputs.new_version }}.ipa"
            mv "$file" "$new_file_name"
          done

      - name: 上传至artifact (${{ matrix.target_platform }})
        if: startsWith(matrix.target_platform, 'android')
        uses: actions/upload-artifact@v4
        with:
          name: PiliPalaX-alpha
          path: |
            build/app/outputs/flutter-apk/Pili-*.apk

      - name: 上传至artifact (iOS)
        if: matrix.target_platform == 'iOS'
        uses: actions/upload-artifact@v4
        with: 
          name: PiliPalaX-alpha
          path: |
            build/Pili-*.ipa

  upload:
    runs-on: ubuntu-latest
    needs: 
      - prepare_publish_info
      - build_matrix
    
    steps:
      - name: 从artifact下载
        uses: actions/download-artifact@v4
        with:
          name: PiliPalaX-alpha
          path: ./PiliPalaX-alpha

      - name: 发送到Telegram频道
        uses: xireiki/channel-post@v1.0.10
        with:
          bot_token: ${{ secrets.BOT_TOKEN }}
          chat_id: ${{ secrets.CHAT_ID }}
          api_id: ${{ secrets.TELEGRAM_API_ID }}
          api_hash: ${{ secrets.TELEGRAM_API_HASH }}
          large_file: true
          method: sendFile
          path: PiliPalaX-alpha/*
          parse_mode: Markdown
          context: "*v${{ needs.prepare_publish_info.outputs.new_version }}:*\n${{ fromJson(needs.prepare_publish_info.outputs.included_commits) }}"      
